source "https://rubygems.org"

group :development do
  gem 'jekyll'
  gem 'haml'
  gem 'hpricot'
  gem 'rdiscount'
  gem 'redcarpet'
  gem 'sass'
  gem 'rake'
  gem 'zurb-foundation'
  gem 'compass'
  gem 'jekyll-tagging'
end
